# Generated by Django 4.2.5 on 2024-03-15 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Home_App", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="static"),
        ),
    ]
