# Generated by Django 4.2.5 on 2024-03-15 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Home_App", "0002_event_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="image",
            field=models.ImageField(
                blank=True,
                height_field=200,
                null=True,
                upload_to="static",
                width_field=100,
            ),
        ),
    ]
