# Generated by Django 4.2.5 on 2024-03-17 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Home_App", "0004_alter_event_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=122)),
                ("email", models.CharField(max_length=122)),
                ("subject", models.TextField(null=True)),
                ("message", models.TextField(null=True)),
                ("date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="UserRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=122)),
                ("course", models.CharField(max_length=100)),
                ("semester", models.IntegerField()),
                ("event_name", models.CharField(max_length=200)),
                ("mobile_no", models.CharField(max_length=15)),
                ("email", models.CharField(max_length=122)),
                ("date", models.DateField()),
            ],
        ),
    ]
