# Generated by Django 4.2.5 on 2024-03-17 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Home_App", "0005_contact_userregistration"),
    ]

    operations = [
        migrations.RenameModel(old_name="Contact", new_name="Contact_Us",),
        migrations.RenameModel(
            old_name="UserRegistration", new_name="User_Registration",
        ),
    ]
