# Generated by Django 4.2.5 on 2024-03-17 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Home_App", "0006_rename_contact_contact_us_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user_registration",
            name="mobile_no",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
