# Generated by Django 4.2.5 on 2024-03-17 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Home_App", "0007_alter_user_registration_mobile_no"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user_registration",
            name="event_name",
            field=models.CharField(blank=True, max_length=122, null=True),
        ),
    ]
