# Generated by Django 4.2.5 on 2024-03-24 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Home_App", "0010_rename_event_name_user_registration_eventname"),
    ]

    operations = [
        migrations.RemoveField(model_name="user_registration", name="eventname",),
    ]
