# Generated by Django 4.2.5 on 2024-03-24 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Home_App", "0011_remove_user_registration_eventname"),
    ]

    operations = [
        migrations.AddField(
            model_name="user_registration",
            name="event_name",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Home_App.event",
            ),
        ),
    ]
