# Generated by Django 4.2.5 on 2024-03-28 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Home_App", "0013_student"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="date_created",
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="email",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="name",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="phone",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
