# Generated by Django 4.2.5 on 2024-03-28 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Home_App", "0014_student_date_created_student_email_student_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="student", name="date_created",),
        migrations.RemoveField(model_name="student", name="email",),
        migrations.RemoveField(model_name="student", name="name",),
        migrations.RemoveField(model_name="student", name="phone",),
    ]
