# Generated by Django 4.2.5 on 2024-03-29 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Home_App", "0017_eventcategory_user_registration_student_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="user_registration", name="category",),
        migrations.RemoveField(model_name="user_registration", name="student",),
        migrations.AddField(
            model_name="event",
            name="category",
            field=models.ManyToManyField(to="Home_App.eventcategory"),
        ),
    ]
