# Generated by Django 4.2.5 on 2024-03-29 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Home_App", "0018_remove_user_registration_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user_registration",
            name="student",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Home_App.student",
            ),
        ),
    ]
