# Generated by Django 4.2.5 on 2024-03-29 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Home_App", "0020_alter_user_registration_student"),
    ]

    operations = [
        migrations.RemoveField(model_name="user_registration", name="student",),
        migrations.AlterField(
            model_name="user_registration",
            name="name",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="Home_App.student",
            ),
        ),
    ]
