# Generated by Django 4.2.5 on 2024-03-31 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Home_App", "0025_remove_user_registration_student_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user_registration",
            name="student",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Home_App.student",
            ),
        ),
        migrations.AlterField(
            model_name="user_registration",
            name="name",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
