# Generated by Django 4.2.5 on 2024-04-02 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Home_App", "0029_student_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="profile_pic",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
