# Generated by Django 4.2.5 on 2024-04-03 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Home_App", "0030_student_profile_pic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="profile_pic",
            field=models.ImageField(blank=True, null=True, upload_to="static/images"),
        ),
    ]
